import t1 from "../assets/techstore/t1.png";
import t2 from "../assets/techstore/t2.png";
import t3 from "../assets/techstore/t3.png";
import t4 from "../assets/techstore/t4.png";
import t5 from "../assets/techstore/t5.png";
import t6 from "../assets/techstore/t6.png";
import t7 from "../assets/techstore/t7.jpeg";
import t8 from "../assets/techstore/t8.jpeg";
import t9 from "../assets/techstore/t9.jpg";
import t10 from "../assets/techstore/t10.jpg";
import t11 from "../assets/techstore/t11.jpg";
import t12 from "../assets/techstore/t12.jpg";
import t13 from "../assets/techstore/t13.jpeg";
import t14 from "../assets/techstore/t14.jpeg";
import t15 from "../assets/techstore/t15.jpeg";
import t16 from "../assets/techstore/t16.jpg";
import t17 from "../assets/techstore/t17.jpeg";
import t18 from "../assets/techstore/t18.jpg";
import t19 from "../assets/techstore/t19.jpg";

import rating4 from "../components/Accordions/rating2.png";

const techstoredata = [
  {
    id: 1,
    image: t1,
    rating: rating4,
    title: "Red iphone 11 64gb",
    price: "998.00",
    body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    orders: 154,
    shipping: "Free Shipping",
  },
  {
    id: 2,
    image: t2,
    rating: rating4,
    title: "black xiaomi note 128gb",
    price: "998.00",
    body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    orders: 154,
    shipping: "Free Shipping",
  },
  {
    id: 3,
    image: t3,
    rating: rating4,
    title: "black Ipad 9 pro 256gb",
    price: "998.00",
    body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo tempor incididunt ut labore et dolore magna aliqua",
    orders: 154,
    shipping: "Free Shipping",
  },
  {
    id: 4,
    image: t4,
    rating: rating4,
    title: "macbook air m1 pro 2022 16gb ram silver",
    price: "998.00",
    body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo tempor incididunt ut labore et dolore magna aliqua",
    orders: 154,
    shipping: "Free Shipping",
  },
  {
    id: 5,
    image: t5,
    rating: rating4,
    title: "Apple Watch Series 8 calls",
    price: "998.00",
    body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    orders: 154,
    shipping: "Free Shipping",
  },
  {
    id: 6,
    image: t6,
    rating: rating4,
    title: "AirPods Max with 5 colors",
    price: "998.00",
    body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    orders: 154,
    shipping: "Free Shipping",
  },
  {
    id: 7,
    image: t2,
    rating: rating4,
    title: "Samsung Galaxy S21 Ultra 5G",
    price: "1,199.99",
    body: "Experience the power of 5G with the Samsung Galaxy S21 Ultra. It features a 6.8-inch Dynamic AMOLED 2X display, 12GB of RAM, and a 5000mAh battery.",
    orders: 267,
    shipping: "Free Shipping",
  },
  {
    id: 8,
    image: t3,
    rating: rating4,
    title: "Apple Watch Series 7",
    price: "399.00",
    body: "Stay connected and in control with the Apple Watch Series 7. It has a larger display, faster charging, and a range of health and fitness features.",
    orders: 521,
    shipping: "Free Shipping",
  },
  {
    id: 9,
    image: t4,
    rating: rating4,
    title: "Dell XPS 13 Laptop",
    price: "1,199.99",
    body: "Experience the ultimate in performance and portability with the Dell XPS 13. It features a 11th Gen Intel Core processor, 16GB of RAM, and a 512GB SSD.",
    orders: 354,
    shipping: "Free Shipping",
  },
  {
    id: 10,
    image: t5,
    rating: rating4,
    title: "Sony PlayStation 5",
    price: "499.99",
    body: "Take your gaming to the next level with the Sony PlayStation 5. It features lightning-fast load times, haptic feedback, and an immersive 3D audio experience.",
    orders: 189,
    shipping: "Free Shipping",
  },
  {
    id: 11,
    image: t6,
    rating: rating4,
    title: "Logitech MX Master 3 Mouse",
    price: "99.99",
    body: "Boost your productivity with the Logitech MX Master 3 mouse. It features advanced scrolling, customizable buttons, and a comfortable ergonomic design.",
    orders: 472,
    shipping: "Free Shipping",
  },
  {
    id: 12,
    image: t7,
    rating: rating4,
    title: "Bose QuietComfort Earbuds",
    price: "279.00",
    body: "Experience the ultimate in noise-canceling technology with the Bose QuietComfort Earbuds. They feature advanced noise cancellation, premium sound quality, and up to 6 hours of battery life.",
    orders: 323,
    shipping: "Free Shipping",
  },
  {
    id: 13,
    image: t8,
    rating: rating4,
    title: "LG OLED65CXPUA 4K TV",
    price: "2,296.99",
    body: "Experience lifelike picture quality with the LG OLED65CXPUA 4K TV. It features a 65-inch OLED display, Dolby Vision IQ, and built-in Google Assistant and Alexa.",
    orders: 122,
    shipping: "Free Shipping",
  },
  {
    id: 14,
    image: t9,
    rating: rating4,
    title: "Microsoft Surface Pro 7",
    price: "1,399.99",
    body: "Get the best of both worlds with the Microsoft Surface Pro 7. It functions as both a laptop and tablet, with ",
    orders: 287,
    shipping: "Free Shipping",
  },
  {
    id: 15,
    image: t10,
    rating: rating4,
    title: "Canon EOS R5 Camera",
    price: "3,899.00",
    body: "Capture stunning photos and videos with the Canon EOS R5 camera. It features a 45MP full-frame sensor, 8K video recording, and in-body image stabilization.",
    orders: 65,
    shipping: "Free Shipping",
  },
  {
    id: 16,
    image: t11,
    rating: rating4,
    title: "Razer Blade 15 Gaming Laptop",
    price: "2,599.99",
    body: "Take your gaming to the next level with the Razer Blade 15 gaming laptop. It features a 10th Gen Intel Core processor, NVIDIA GeForce RTX graphics, and a 15.6-inch Full HD display.",
    orders: 142,
    shipping: "Free Shipping",
  },
  {
    id: 17,
    image: t12,
    rating: rating4,
    title: "black Apple AirPods Pro",
    price: "249.00",
    body: "Experience premium sound quality and noise cancellation with the Apple AirPods Pro. They feature a comfortable, in-ear design and up to 4.5 hours of battery life.",
    orders: 759,
    shipping: "Free Shipping",
  },
  {
    id: 18,
    image: t13,
    rating: rating4,
    title: "Samsung Odyssey G9 Gaming Monitor",
    price: "1,499.99",
    body: "Immerse yourself in your favorite games with the Samsung Odyssey G9 gaming monitor. It features a 49-inch curved QLED display, 240Hz refresh rate, and 1ms response time.",
    orders: 89,
    shipping: "Free Shipping",
  },
  {
    id: 19,
    image: t14,
    rating: rating4,
    title: "silver Lenovo Legion 5 Gaming Laptop",
    price: "1,199.99",
    body: "Dominate the competition with the Lenovo Legion 5 gaming laptop. It features a 10th Gen Intel Core processor, NVIDIA GeForce RTX graphics, and a 15.6-inch Full HD display.",
    orders: 215,
    shipping: "Free Shipping",
  },
  {
    id: 20,
    image: t15,
    rating: rating4,
    title: "Bose SoundLink Revolve+ Bluetooth Speaker",
    price: "299.00",
    body: "Experience 360-degree sound with the Bose SoundLink Revolve+ Bluetooth speaker. It features a water-resistant design, up to 16 hours of battery life, and built-in voice prompts.",
    orders: 491,
    shipping: "Free Shipping",
  },
  {
    id: 21,
    image: t16,
    rating: rating4,
    title: "Sony WH-1000XM4 Wireless Headphones",
    price: "349.99",
    body: "Experience the ultimate in noise-canceling headphones with the Sony WH-1000XM4. They feature advanced noise cancellation, premium sound quality, and up to 30 hours of battery life.",
    orders: 386,
    shipping: "Free Shipping",
  },
  {
    id: 22,
    image: t17,
    rating: rating4,
    title: "white Apple AirPods Pro",
    price: "249.00",
    body: "Experience active noise cancellation and immersive sound with the Apple AirPods Pro. With a customizable fit and sweat and water resistance, these wireless earbuds are perfect for any lifestyle.",
    orders: 231,
    shipping: "Free Shipping",
  },
  {
    id: 23,
    image: t18,
    rating: rating4,
    title: "curved Samsung Odyssey G9 Gaming Monitor",
    price: "1,399.99",
    body: "Immerse yourself in gaming with the Samsung Odyssey G9 Gaming Monitor. This 49-inch monitor features a 1000R curved screen, 240Hz refresh rate, and NVIDIA G-Sync compatibility for a smooth and responsive gaming experience.",
    orders: 86,
    shipping: "Free Shipping",
  },
  {
    id: 24,
    image: t19,
    rating: rating4,
    title: "Lenovo Legion 5 Gaming Laptop",
    price: "1,199.99",
    body: "Get a competitive edge with the Lenovo Legion 5 Gaming Laptop. This laptop features a 10th Gen Intel Core processor, NVIDIA GeForce RTX graphics, and a 15.6-inch Full HD display for immersive gameplay.",
    orders: 184,
    shipping: "Free Shipping",
  },
];
export default techstoredata;
